from app.schemas.auth import (
    MessageResponse,
    RegisterResponse,
    ResendVerificationRequest,
    Token,
    UniversityLookupResponse,
    UserLogin,
    UserOut,
    UserRegister,
    UserUpdate,
    UniversityOut,
    VerifyTokenRequest,
)
from app.schemas.content import (
    AuthorOut,
    CommentCreate,
    CommentOut,
    PostCreate,
    PostFeedQuery,
    PostOut,
    VoteIn,
)

__all__ = [
    "MessageResponse",
    "RegisterResponse",
    "ResendVerificationRequest",
    "Token",
    "UniversityLookupResponse",
    "UserLogin",
    "UserOut",
    "UserRegister",
    "UserUpdate",
    "UniversityOut",
    "VerifyTokenRequest",
    "AuthorOut",
    "CommentCreate",
    "CommentOut",
    "PostCreate",
    "PostFeedQuery",
    "PostOut",
    "VoteIn",
]
